/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 watermelon.glb --transform 
Files: watermelon.glb [3.56MB] > watermelon-transformed.glb [356.74KB] (90%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Watermelon(props) {
  const { nodes, materials } = useGLTF('/watermelon-transformed.glb')
  return (
    <group {...props} dispose={null}>
      {/* <mesh geometry={nodes.base.geometry} material={materials.PaletteMaterial001} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['base-glass'].geometry} material={materials.Bottom_textured_1} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['center-glass'].geometry} material={materials.watermelon_inside_textured_1} rotation={[-Math.PI / 2, 0, 0]} /> */}
      {/* <mesh geometry={nodes['front-shine'].geometry} material={materials.PaletteMaterial002} rotation={[-Math.PI / 2, 0, 0]} /> */}
    </group>
  )
}

useGLTF.preload('/watermelon-transformed.glb')
